title: Introduction to Big Data Processing Final Project
description: Welcome to my web page! This page was created for the final presentation of Introduction to Big Data Processing course at the University of Bologna.
theme: jekyll-theme-modernist
