title: Introduction to Big Data Processing
description: Welcome to my web page! This is the final presentation of Introduction to Big Data Processing course of the University of Bologna.
theme: jekyll-theme-modernist
